In [1]:
import numpy as np

## **Arrays creation and shape**

In [2]:
a = np.arange(3 * 4) #[ 0  1  2  3  4  5  6  7  8  9 10 11]
b = np.arange(3 * 4).reshape((3, 4))
c = np.arange(3 * 4 * 2).reshape((3, 4, 2))

print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


## **Indexing**

In [3]:
a = np.arange(3 * 4).reshape((3, 4))
b = np.arange(3 * 4)


a[0, :] = 99 # will set all elements of first row (axis=0) to 99
print(a)
a[:, 1] = 104 # will set all elements of second column (axis=1) to 104 
print(a)

print(b)
print(b[-1])
print(b[-2])

print(a[-1, :])  # take last element
print(a[:, 0:3]) # exclude last column


[[99 99 99 99]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 99 104  99  99]
 [  4 104   6   7]
 [  8 104  10  11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
10
[  8 104  10  11]
[[ 99 104  99]
 [  4 104   6]
 [  8 104  10]]


### Numpy is row major
We access the row as first element and then each column. We access row before columns.

In [4]:
a = np.arange(3 * 4).reshape((3, 4))

print(a)
print("first row = ", a[0])
print("last row  = ", a[2])
print("second column = ", a[:, 1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row =  [0 1 2 3]
last row  =  [ 8  9 10 11]
second column =  [1 5 9]


## **Vector operations**

### Matrix multiplication

In [5]:
a = np.arange(3 * 4).reshape((3, 4))
b = np.arange(4 * 5).reshape((4, 5)) #4 == 4 requiered
c = a @ b

print(a)
print(b)
print(c)
print(a.shape, " x ", b.shape, " = ", c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]
(3, 4)  x  (4, 5)  =  (3, 5)


### Matrix vector multiplication (vectors as columns)

In [6]:
a = np.arange(3 * 4).reshape((3, 4))
b = np.arange(4 * 1).reshape((4, 1)) #must have shape [[], [], []] !

c = a @ b
d = a.dot

print(a)
print(b)
print(c)

print(a.shape, " x ", b.shape, " = ", c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[[14]
 [38]
 [62]]
(3, 4)  x  (4, 1)  =  (3, 1)


### Matrix vector multiplication (vectors as rows)

In [7]:
a = np.arange(3 * 4).reshape((3, 4))
a = a.T # to get same result as above
b = np.arange(4 * 1).reshape((4, 1))
b = b.T

c = b @ a # inversed order !

print(a)
print(b)
print(c)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 1 2 3]]
[[14 38 62]]


### Dot product (vectors as columns)

In [8]:
a = np.arange(4 * 1).reshape((4, 1))
b = np.arange(4 * 1).reshape((4, 1))

c = a.T @ b
d = np.dot(a.T, b)

print(a)
print(b)
print(c)
print(c == d)

[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]
[[14]]
[[ True]]


### Dot product (vectors as rows)

In [9]:
a = np.arange(4 * 1).reshape((4, 1))
b = np.arange(4 * 1).reshape((4, 1))
a = a.T # to get same result as above
b = b.T

c = a @ b.T # reversed order !

print(a)
print(b)
print(c)

[[0 1 2 3]]
[[0 1 2 3]]
[[14]]


### Euclidean norm

In [10]:
a = np.ones((3, 4)) * 2 #seen as 4 3-D vectors (convention?) or 3 4-D vectors
b = np.ones((3, 1))
c = np.linalg.norm(a - b) #norm a as a flattened array
d = np.linalg.norm(a, axis=0) #norm as 4 3-D arrays
e = np.linalg.norm(a, axis=1) #norm as 3 4-D arrays

print(a)
print(b)
print(c)
print(d)
print(e)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[1.]
 [1.]
 [1.]]
3.4641016151377544
[3.46410162 3.46410162 3.46410162 3.46410162]
[4. 4. 4.]


### Euclidean norm of vector with vectors (vector as columns)

In [11]:
# 3D vectors along columns
a = np.arange(3 * 4).reshape((3, 4))
b = a[:, 1].reshape((3, 1)) #b is the second vector of a
c = np.linalg.norm(a - b, axis=0)

print(a)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1]
 [5]
 [9]]
[1.73205081 0.         1.73205081 3.46410162]


### Euclidean norm of vector with vectors (vectors as rows)

In [12]:
# 3D vectors along rows
a = np.arange(3 * 4).reshape((3, 4)) # vector as columns
a = a.T # vectors as rows (np.arange(4 * 3).reshape((4, 3)))
b = a[1, :].reshape((1, 3)) #mind that we flipped the vector as a row otherwise need to transpose
c = np.linalg.norm(a - b, axis=1)

print(a)
print(b)
print(c)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[1 5 9]]
[1.73205081 0.         1.73205081 3.46410162]


### A few words about matrix (or Array in 2D) representation in Numpy

In row major system we index the data first by row and then by column. Therefore, any vector span along axis=1 and all vectors are listed along axis=0. You can represents a matrix with vector as columns in a row major system but this is not intuitive. In a row major system, if matrix are represented as columns of vectors, axis 0 spans the vectors and axis 1 spans the elements. If matrix are represented as row of vectors, axis 0 spans the vectors themselves and then axis 1 spans the components.

**Convention**: In numpy we should represent the matrix following the natural row major order. Therefore, rows of matrix should be the vectors.

### Try out

In [15]:
a = np.array([
    [1, 2, -1],
    [1, 4, 2],
    [3, 5, 4]
])

Z = a[:, 2]
idx = np.arange(a.shape[0])
idx = idx[Z[idx] > 0]

print(a[idx])


[[1 4 2]
 [3 5 4]]
