In [1]:
import numpy as np

## **Arrays creation and shape**

In [20]:
a = np.arange(3 * 4) #[ 0  1  2  3  4  5  6  7  8  9 10 11]
b = np.arange(3 * 4).reshape((3, 4))
c = np.arange(3 * 4 * 2).reshape((3, 4, 2))

print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


## **Indexing**

In [21]:
a = np.arange(3 * 4).reshape((3, 4))

a[0, :] = 99 # will set all elements of first row (axis=0) to 99
print(a)
a[:, 1] = 104 # will set all elements of second column (axis=1) to 104 
print(a)

[[99 99 99 99]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 99 104  99  99]
 [  4 104   6   7]
 [  8 104  10  11]]


### Numpy is row major
We access the row as first element and then each column. We access row before columns.

In [49]:
a = np.arange(3 * 4).reshape((3, 4))

print(a)
print("first row = ", a[0])
print("last row  = ", a[2])
print("second column = ", a[:, 1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row =  [0 1 2 3]
last row  =  [ 8  9 10 11]
second column =  [1 5 9]


## **Vector operations**

### Matrix multiplication

In [19]:
a = np.arange(3 * 4).reshape((3, 4))
b = np.arange(4 * 5).reshape((4, 5)) #4 == 4 requiered
c = a @ b

print(a)
print(b)
print(c)
print(a.shape, " x ", b.shape, " = ", c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]
(3, 4)  x  (4, 5)  =  (3, 5)


### Matrix vector multiplication (vectors as columns)

In [24]:
a = np.arange(3 * 4).reshape((3, 4))
b = np.arange(4 * 1).reshape((4, 1)) #must have shape [[], [], []] !

c = a @ b
d = a.dot

print(a)
print(b)
print(c)

print(a.shape, " x ", b.shape, " = ", c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[[14]
 [38]
 [62]]
(3, 4)  x  (4, 1)  =  (3, 1)


### Matrix vector multiplication (vectors as rows)

In [52]:
a = np.arange(3 * 4).reshape((3, 4))
a = a.T # to get same result as above
b = np.arange(4 * 1).reshape((4, 1))
b = b.T

c = b @ a # inversed order !

print(a)
print(b)
print(c)



[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 1 2 3]]
[[14 38 62]]


### Dot product (vectors as columns)

In [54]:
a = np.arange(4 * 1).reshape((4, 1))
b = np.arange(4 * 1).reshape((4, 1))

c = a.T @ b
d = np.dot(a.T, b)

print(a)
print(b)
print(c)
print(c == d)

[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]
[[14]]
[[ True]]


### Dot product (vectors as rows)

In [55]:
a = np.arange(4 * 1).reshape((4, 1))
b = np.arange(4 * 1).reshape((4, 1))
a = a.T # to get same result as above
b = b.T

a @ b.T

print(a)
print(b)
print(c)

[[0 1 2 3]]
[[0 1 2 3]]
[[14]]


### Euclidean norm

In [38]:
a = np.ones((3, 4)) * 2 #seen as 4 3-D vectors (convention?) or 3 4-D vectors
b = np.ones((3, 1))
c = np.linalg.norm(a - b) #norm a as a flattened array
d = np.linalg.norm(a, axis=0) #norm as 4 3-D arrays
e = np.linalg.norm(a, axis=1) #norm as 3 4-D arrays

print(a)
print(b)
print(c)
print(d)
print(e)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[1.]
 [1.]
 [1.]]
3.4641016151377544
[3.46410162 3.46410162 3.46410162 3.46410162]
[4. 4. 4.]


### Euclidean norm of vector with vectors (vector as columns)

In [42]:
# 3D vectors along columns
a = np.arange(3 * 4).reshape((3, 4))
b = a[:, 1].reshape((3, 1)) #b is the second vector of a
c = np.linalg.norm(a - b, axis=0)

print(a)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1]
 [5]
 [9]]
[1.73205081 0.         1.73205081 3.46410162]


### Euclidean norm of vector with vectors (vectors as rows)

In [47]:
# 3D vectors along rows
a = np.arange(3 * 4).reshape((3, 4)) # vector as columns
a = a.T # vectors as rows (np.arange(4 * 3).reshape((4, 3)))
b = a[1, :].reshape((1, 3)) #mind that we flipped the vector as a row otherwise need to transpose
c = np.linalg.norm(a - b, axis=1)

print(a)
print(b)
print(c)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[1 5 9]]
[1.73205081 0.         1.73205081 3.46410162]


### A few words about matrix representation in Numpy

In row major system we represent the matrix as row of vectors. Therefore, any vector span along axis=1 and all vectors are listed along axis=0. You can represents a matrix with vector as columns in a row major system but this is not intuitive.