In [1]:
import torch

### Dimensions in pytorch

In [28]:
x = torch.arange(6 * 3)              # torch.Size([18])


x = torch.arange(6 * 3).view((6, 3)) # torch.Size([6, 3]) -> dim0 = 6 and dim1 = 3

"""
Here we build a tensor as a 6x3 matrix. In fact, this is a tensor containing 
6 tensors each being a tensor of 3 elements.

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

"""

x = torch.arange(6 * 3 * 2).view((6, 3, 2))

"""

Here we build a tensor with 6 tensors, each being a 3x2 tensor
What we see bellow are the slices of each tensors.

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]])
         
"""

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]])

In [20]:
x = torch.arange(6 * 3).view((6, 3))
y = torch.arange(6)

x[:, 0]
print(x)
print(y)
print(x * y)


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
tensor([0, 1, 2, 3, 4, 5])


RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1